#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [Container_ID]"
}

function container_list() {
    echo
    echo Container list:
    docker ps -a
}

if [ -z "${1}" ]; then
    usage
    container_list
    exit 1
fi

cid=${1}

echo docker attach ${cid}
docker attach  ${cid}
