#!/bin/bash
echo docker network prune -f
docker network prune -f
echo

echo docker volume prune -f
docker volume prune -f
echo

echo docker container prune -f
docker container prune -f
echo

echo docker system prune -f
docker system prune -f
echo

# remove none tag images
# refer to https://stackoverflow.com/questions/33913020/docker-remove-none-tag-images
#docker image rm -f $(docker images -f dangling=true -q)
imgs=$(docker images -f dangling=true -q)
if [ ! -z "${imgs}" ]; then
    docker image rm -f ${imgs}
fi

echo docker network ls
docker network ls
echo

echo docker volume ls
docker volume ls
echo

echo docker ps -a
docker ps -a
echo

echo docker system df
docker system df
