#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [Container_ID] [Command]"
    echo "example:"
    echo "    ${ME} 123456789012 uname -a"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

if [ -z "${2}" ]; then
    usage
fi

ctrid=${1}


echo docker exec -t ${ctrid} "${@:2}"
docker exec -t ${ctrid} "${@:2}"
