#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [Image_Name_1] [Image_Name_2] ..."
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

#name=${1}
#echo docker rmi -f ${name}
#docker rmi -f ${name}

for imgname in $@; do
    echo docker rmi -f ${imgname}
    docker rmi -f ${imgname}
done
