#!/bin/bash
echo docker network ls
docker network ls
echo

echo docker volume ls
docker volume ls
echo

# List all tcp port mappings
# docker ps --format "{{.Ports}}"
echo all tcp port mappings
docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a
echo

echo docker image ls
docker image ls
