#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [Image_Name]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

name=${1}

echo docker run --rm -it ${name} bash
docker run --rm -it ${name} bash
