#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [Container_ID_1] [Container_ID_2] ..."
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

#ctrid=${1}
#echo docker rm -f ${ctrid}
#docker rm -f ${ctrid}

for ctrid in $@; do
    echo docker rm -f ${ctrid}
    docker rm -f ${ctrid}
done
