#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [Container_ID]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

ctrid=${1}

echo docker rm -f ${ctrid}
docker rm -f ${ctrid}
