#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [Container_ID]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

cid=${1}

#docker exec -it ${cid} sh

echo docker exec -it ${cid} /bin/sh
docker exec -it ${cid} /bin/sh
